name: Build and Test

on: 
  push:
    branches: [ master ]
    paths:
    - 'ConsoleActions/**'
    - 'SampleREPL/**'
    - '.github/workflows/**'
env:
  Configuration: Release
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1

    - name: Build Projects
      run: dotnet build --configuration ${{ env.Configuration }}
    - name: Run Tests
      run: dotnet test ConsoleActions.Tests/ConsoleActions.Tests.csproj --configuration ${{ env.Configuration }}
